version: "3.8"

services:
  postgres:
    image: postgres:15.2-alpine
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  basket-data:
    image: redis:7.0.8-alpine
  
  seq:
    image: datalust/seq:latest
  
  basket-api:
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on:
      - basket-data
      - rabbitmq

  catalog-api:
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
  
  keycloak:
    image: jboss/keycloak