version: "3.8"

services:
  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  basket-data:
    ports:
      - "6379:6379"
  
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5099:80"

  basket-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RABBITMQ__HOST=host.docker.internal
      - BASKETSETTINGS__REDISCONNECTIONSTRING=host.docker.internal
      - SEQ__HOST=http://host.docker.internal:5099
    ports:
      - "5002:80"

  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RABBITMQ__HOST=host.docker.internal
      - CONNECTIONSTRINGS__DEFAULT=User ID=postgres;Password=postgres;Host=host.docker.internal;Port=5432;Database=EShop.Catalog;
      - SEEDDBCONTEXT=true
      - SEQ__HOST=http://host.docker.internal:5099
    ports:
      - "5001:80"
  
  keycloak:
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=host.docker.internal
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres

volumes:
  postgres:
